apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: fast-build-run-
spec:
  pipelineRef:
    name: fast-build-pipeline
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi